### ISSUE TITLE
Error when trying to access https://cid.fhtrue.com/ConfigClients.aspx

### ISSUE THREAD

**Issue by njosefbeck** [FHDevelopment/fhCID#1]
I'm trying to set up a client in CID and am getting an error when I go to the following URL:
https://cid.fhtrue.com/ConfigClients.aspx

I'll try to look into it, but if someone like @walshmp or @Goswamiv has a moment to take a look, that'd be much appreciated! Thanks!

**Comment by Goswamiv** [comment]
Alright...I have reached to this point now where I am able to debug this on my local. I am on it.

**Comment by Goswamiv** [comment]
@donmox , @njosefbeck  - seems to be fixed now. I am closing this...fee free to reopen.
I will be working on getting CID jobs move to new server now.

Sorry for all the trouble - was just trying to understand the CID.
