### ISSUE TITLE
Remove 'Fleishman' from the email that CID sends out

### ISSUE THREAD

**Issue by njosefbeck** [FHDevelopment/fhCID#3]
![image](https://cloud.githubusercontent.com/assets/9508002/12246975/4279006e-b877-11e5-83f2-56f46265f52d.png)

**Comment by Goswamiv** [comment]
![image](https://cloud.githubusercontent.com/assets/13023653/12311456/be553e72-ba1c-11e5-9766-7f1de08802ab.png)

deployed the latest code and verified. closing this issue as it looks to be fixed.
